apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: s4bhrm8na-python 
  janus-idp.io/tekton: s4bhrm8na-python
  backstage.io/kubernetes-id: s4bhrm8na-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: s4bhrm8na-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml