apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: s4bhrm8na-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:0871584ce64e461bac10b7125d1b82a16c3c6cbb@sha256:d1bf67cbeb489032caf9a0bdb1ac7f3c530c8fe4576158cac1a2ce4990e8e7ca
          name: container-image
